### ISSUE TITLE
Error downloading Album

### ISSUE THREAD

**Issue by ShadyRelapse-PP** [yarrm80s/orpheusdl-qobuz#6]
Hello I get this error when trying to download this album:
Traceback (most recent call last):
  File "C:\Users\User\Desktop\orpheusdl-master\orpheus.py", line 223, in <module>
    main()
  File "C:\Users\User\Desktop\orpheusdl-master\orpheus.py", line 218, in main
    orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
  File "C:\Users\User\Desktop\orpheusdl-master\orpheus\core.py", line 381, in orpheus_core_download
    downloader.download_album(media_id, extra_kwargs=media.extra_kwargs)
  File "C:\Users\User\Desktop\orpheusdl-master\orpheus\music_downloader.py", line 168, in download_album
    self.download_track(track_id, album_location=album_path, track_index=index, number_of_tracks=number_of_tracks, main_artist=artist_name, cover_temp_location=cover_temp_location, indent_level=indent_level+1, extra_kwargs=album_info.track_extra_kwargs)
  File "C:\Users\User\Desktop\orpheusdl-master\orpheus\music_downloader.py", line 220, in download_track
    track_info: TrackInfo = self.service.get_track_info(track_id, quality_tier, codec_options, **extra_kwargs)
  File "C:\Users\User\Desktop\orpheusdl-master\modules\qobuz\interface.py", line 53, in get_track_info
    for credit in track_data['performers'].split(' - '):
KeyError: 'performers'

 https://www.qobuz.com/us-en/album/growth-jon-bellion/0060256713278

**Comment by yarrm80s** [comment]
@ShadyRelapse-PP Oh that's a bug, I'll have to fix it

**Comment by z0rg0n** [comment]
Same error happens with these two albums:

https://open.qobuz.com/album/zh6zxnp5yzxhc
https://open.qobuz.com/album/0884977900507

In the second album it happens on track 2 which I guess means it's related to whatever additional DRM qobuz has on that track.
![Screenshot from 2022-03-10 08-26-56](https://user-images.githubusercontent.com/82673289/157695113-1e020c02-d105-4c1e-b2fb-29617737b0a7.png)

**Comment by yarrm80s** [comment]
@z0rg0n It's not related to DRM, just a bug where I assume Qobuz is giving me some data it very rarely doesn't. I forgot to fix it, whoops

**Comment by z0rg0n** [comment]
Totally fixed on the orpheusdl end. Turns out Qobuz only gives 30s of streaming for certain tracks like the ones grayed out in my above screen shot. Orpheusdl will download that 30s now but for the complete tracks you'd have to look elsewhere.

**Comment by Dniel97** [comment]
Just added a check to skip those 30 seconds tracks completely, because they are listed as `"streamable": False` anyway.
