### ISSUE TITLE
Unable to download a complete album (Qobuz)

### ISSUE THREAD

**Issue by fnurre3** [yarrm80s/orpheusdl-qobuz#8]
OS: Ubuntu 18.04.6 LTS

Album: https://open.qobuz.com/album/0060249889084

I'm using the latest repo of qobuz module and orpheusdl.

I'm getting the following error:

> Track 20/24
>         === Downloading track Kill You (4334360) ===
>                 Artists: Eminem (46971)
>                 Release year: 2005
>                 Codec: FLAC, bit depth: 16bit, sample rate: 44.1kHz
> 
>                 Downloading track file
>                 100%|███████████████████████████ 24.1M/24.1M [00:00<00:00, 117MB/s]
>                 Retrieving lyrics with musixmatch
>                 Lyrics module could not find any lyrics.
>                 Retrieving credits
>                 Tagging file
>         === Track 4334360 downloaded ===
> 
>         Track 21/24
> Traceback (most recent call last):
>   File "/opt/orpheusdl/orpheus.py", line 223, in <module>
>     main()
>   File "/opt/orpheusdl/orpheus.py", line 218, in main
>     orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
>   File "/opt/orpheusdl/orpheus/core.py", line 381, in orpheus_core_download
>     downloader.download_album(media_id, extra_kwargs=media.extra_kwargs)
>   File "/opt/orpheusdl/orpheus/music_downloader.py", line 170, in download_album
>     self.download_track(track_id, album_location=album_path, track_index=index, number_of_tracks=number_of_tracks, main_artist=artist_name, cover_temp_location=cover_temp_location, indent_level=indent_level+1, extra_kwargs=album_info.track_extra_kwargs)
>   File "/opt/orpheusdl/orpheus/music_downloader.py", line 222, in download_track
>     track_info: TrackInfo = self.service.get_track_info(track_id, quality_tier, codec_options, **extra_kwargs)
>   File "/opt/orpheusdl/modules/qobuz/interface.py", line 49, in get_track_info
>     unicodedata.normalize('NFKD', track_data['performer']['name'])
> KeyError: 'performer'

I guess Qobuz doesn't have an artist name for this track, probably why this error.

Any fix would be appreciated.

**Comment by Dniel97** [comment]
That was exactly the case! On the web version the artist was missing and the mobile version had a fallback to "Rufus Johnson" which doesn't seem quite right to me. So I implemented a fallback to the album artist.
